# Generated by Django 6.0.6 on 2026-07-05 17:48

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_databasefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagememory',
            name='image',
            field=models.ImageField(storage=api.storage.DatabaseStorage(), upload_to='memories/'),
        ),
    ]
